# Generated by Django 3.2.2 on 2021-05-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectdetail',
            options={'verbose_name': 'Project Detail', 'verbose_name_plural': 'Project Details'},
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_detail_description',
            field=models.TextField(),
        ),
    ]
