# Generated by Django 3.2.2 on 2021-05-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/photography')),
                ('photo_caption', models.CharField(max_length=100)),
            ],
        ),
    ]
