# Generated by Django 3.2.2 on 2021-05-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photography',
            options={'verbose_name': 'Photograph', 'verbose_name_plural': 'Photographs'},
        ),
    ]
